name: Deploy ELK to AKS

on:
   workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    permissions:
       id-token: write
       contents: read

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: Azure login 
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: snk
          cluster-name: snk-helm

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Create Namespace (If not exists)
        run: |
           kubectl create namespace elastic-system || true
      # To check the helm charts is available or not?
      - name: Check if Helm release exists
        run: |
          helm repo add elastic https://helm.elastic.co
          helm repo update
          helm upgrade --install eck-operator elastic/eck-operator \
           --namespace elastic-system \
           --set installCRDs=true
           
      - name: Fetch Helm Repo list
        run: | 
           helm repo ls
      - name: List Helm charts
        run: | 
           helm ls -A








      
  
